### ISSUE TITLE
TiffImages.SOFTWARE tag overwritten during saving

### ISSUE THREAD

**Issue by grhartl** [tlnagy/TiffImages.jl#60]
The Software tag seems to be fixed during saving to something like "TiffImages.jl v0.4.1" .
While I agree that this is the suitable spot, it would be great if this is already done before saving, so also shows up right after generating the DenseTaggedImage, instead of silently overwriting the current software tag during saving.

**Comment by tlnagy** [comment]
That's fair. I would need to look up what is the generally accepted practice for updating the SOFTWARE tag when saving a TIFF. Is it overwritten? Or appended? Or preserved?

**Comment by grhartl** [comment]
According to [loc](https://www.loc.gov/preservation/digital/formats/content/tiff_tags.shtml) I would suggest appending, seperated by ";"

**Comment by tlnagy** [comment]
That seems reasonable to me. I would be happy to review a PR if you have time to make one, otherwise I'll add it to my queue of things to do. 

I overwrite the SOFTWARE tag here: 

https://github.com/tlnagy/TiffImages.jl/blob/18e6b45a98885533452a2b7c42fd44af97405b47/src/types/dense.jl#L110

The proper solution is likely to check if there's already anything in the tag and append if so, otherwise just write to the tag.

**Comment by tlnagy** [comment]
The dev version of TiffImages should now support appending the software tag instead of overwriting it by default!
